routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['as' => 'admin.'], function(){

    Route::resource('companies', 'Admin\CompanyController')->except(['show']);
    Route::resource('clients', 'Admin\ClientController')->except(['show']);

});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Company
 * @package App\Models
 * @property string $first_name
 * @property string $last_name
 */
class Client extends Model
{
    protected $fillable = [
        'first_name',
        'last_name'
    ];

    /**
     * The roles that belong to the user.
     */
    public function companies()
    {
        return $this->belongsToMany(Company::class, 'company_client');
    }
}

app/Http/Controllers/API/ClientController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Client;
use Illuminate\Http\Request;

class ClientController extends APIController
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return $this->getList($request, Client::class, [ 'first_name', 'last_name' ], [], ['companies']);
    }

    public function getClientCompanies(Request $request, Client $client)
    {
        return response()->json($client->companies);
    }
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Client;
use App\Http\Requests\Admin\Client\{StoreClientRequest, UpdateClientRequest};
use App\Http\Controllers\Controller;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();

        return view('admin.clients.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreClientRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreClientRequest $request)
    {
        $validated = $request->validated();

        $client = Client::create($validated);

        return redirect(route('admin.clients.edit', ['client' => $client->id]))
            ->with('success', 'Client created successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Client $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('admin.clients.edit', ['client' => $client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateClientRequest  $request
     * @param  Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateClientRequest $request, Client $client)
    {
        $validated = $request->validated();

        $client->update($validated);

        return redirect(route('admin.clients.edit', ['client' => $client->id]))
            ->with('success', 'Client updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Client $client
     * @return void
     * @throws \Exception
     */
    public function destroy(Client $client)
    {
        $client->delete();

        session()->flash('success', 'Client "' . $client->first_name  . " " . $client->last_name . '" deleted successfully');
    }
}

resources/views/admin/clients/create.blade.php
@extends('adminlte::page')

@section('title', 'Clients')

@section('content')

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Create client</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{ route('admin.clients.store') }}">
                    {{ csrf_field() }}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="first_name">First name</label>
                            <input
                                    type="text"
                                    name="first_name"
                                    class="form-control @error('first_name') is-invalid @enderror"
                                    placeholder="First name"
                            >

                            @error('first_name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="last_name">First name</label>
                            <input
                                type="text"
                                name="last_name"
                                class="form-control @error('last_name') is-invalid @enderror"
                                placeholder="Last name"
                            >

                            @error('last_name')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
        <!--/.col (left) -->
    </div>
@stop

resources/views/admin/clients/edit.blade.php
@extends('adminlte::page')

@section('title', 'Clients')

@section('content')

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit client</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{ route('admin.clients.update', ['client' => $client->id]) }}">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">
                    <div class="box-body">

                        <div class="form-group">
                            <label for="first_name">First name</label>
                            <input
                                type="text"
                                name="first_name"
                                class="form-control @error('first_name') is-invalid @enderror"
                                placeholder="First name"
                                value="{{ old('first_name', $client->first_name) }}"
                            >

                            @error('first_name')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="last_name">Last name</label>
                            <input
                                type="text"
                                name="last_name"
                                class="form-control @error('last_name') is-invalid @enderror"
                                placeholder="Last name"
                                value="{{ old('last_name', $client->last_name) }}"
                            >

                            @error('last_name')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>


                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
        <!--/.col (left) -->
    </div>
@stop

resources/views/admin/clients/list.blade.php
@extends('adminlte::page')

@section('title', 'Companies')

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Clients</h3>
            <a href="{{ route('admin.clients.create') }}">Create client</a>
        </div>

        <br>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="clients" class="table table-bordered table-hover dataTable" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Companies count</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Companies count</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@stop

@section('js')
    <script>

        $(document).ready(function() {
            $('#clients').DataTable( {
                serverSide: true,
                ajax: {
                    url: "{{ route('api.clients.index') }}",
                    dataSrc: 'data'
                },
                columns: [
                    { data: 'id' },
                    { data: 'first_name' },
                    { data: 'last_name' },
                    { data: 'companies_count' },
                    {
                        sortable: false,
                        "render": function ( data, type, full, meta ) {
                            let href = '/clients/' + full.id + '/edit';
                            return '<a href="' + href + '"  >Edit</a>';
                        }
                    },
                    {
                        sortable: false,
                        "render": function ( data, type, full, meta ) {
                            let href = '/clients/' + full.id;
                            return '<a href="#" data-href="' + href + '" class="remove-item" >Delete</a>';
                        }
                    }
                ]
            });
        });

    </script>
@stop