routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['as' => 'admin.'], function(){

    Route::resource('companies', 'Admin\CompanyController')->except(['show']);
    Route::resource('clients', 'Admin\ClientController')->except(['show']);

});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Company
 * @package App\Models
 * @property string $name
 */
class Company extends Model
{
    protected $fillable = [
        'name'
    ];

    /**
     * The roles that belong to the user.
     */
    public function clients()
    {
        return $this->belongsToMany(Client::class, 'company_client');
    }
}

app/Http/Controllers/API/CompanyController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Company;
use Illuminate\Http\Request;

class CompanyController extends APIController
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return $this->getList($request, Company::class, [ 'name' ], [], ['clients']);
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Company;
use App\Http\Requests\Admin\Company\{StoreCompanyRequest, UpdateCompanyRequest};
use App\Http\Controllers\Controller;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();

        return view('admin.companies.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreCompanyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCompanyRequest $request)
    {
        $validated = $request->validated();

        $company = Company::create($validated);

        return redirect(route('admin.companies.edit', ['company' => $company->id]))
                ->with('success', 'Company created successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('admin.companies.edit', ['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateCompanyRequest  $request
     * @param  Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCompanyRequest $request, Company $company)
    {
        $validated = $request->validated();

        $company->update($validated);

        return redirect(route('admin.companies.edit', ['company' => $company->id]))
            ->with('success', 'Company updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Company $company
     * @return void
     * @throws \Exception
     */
    public function destroy(Company $company)
    {
        $company->delete();

        session()->flash('success', 'Company "' . $company->name . '" deleted successfully');
    }
}

resources/views/admin/companies/create.blade.php
@extends('adminlte::page')

@section('title', 'Companies')

@section('content')

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Create company</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{ route('admin.companies.store') }}">
                    {{ csrf_field() }}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name">Company name</label>
                            <input
                                    type="text"
                                    name="name"
                                    class="form-control @error('title') is-invalid @enderror"
                                    placeholder="Enter name"
                            >

                            @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
        <!--/.col (left) -->
    </div>
@stop

resources/views/admin/companies/edit.blade.php
@extends('adminlte::page')

@section('title', 'Companies')

@section('content')

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit company</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{ route('admin.companies.update', ['company' => $company->id]) }}">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name">Company name</label>
                            <input
                                type="text"
                                name="name"
                                class="form-control @error('title') is-invalid @enderror"
                                placeholder="Enter name"
                                value="{{ old('name', $company->name) }}"
                            >

                            @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
        <!--/.col (left) -->
    </div>
@stop

resources/views/admin/companies/list.blade.php
@extends('adminlte::page')

@section('title', 'Companies')

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Companies</h3>
            <a href="{{ route('admin.companies.create') }}">Create company</a>
        </div>

        <br>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="companies" class="table table-bordered table-hover dataTable" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Clients count</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Clients count</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@stop

@section('js')
    <script>

        $(document).ready(function() {
            $('#companies').DataTable( {
                serverSide: true,
                ajax: {
                    url: "{{ route('api.companies.index') }}",
                    dataSrc: 'data'
                },
                columns: [
                    { data: 'id' },
                    { data: 'name' },
                    { data: 'clients_count' },
                    {
                        sortable: false,
                        "render": function ( data, type, full, meta ) {
                            let href = '/companies/' + full.id + '/edit';
                            return '<a href="' + href + '"  >Edit</a>';
                        }
                    },
                    {
                        sortable: false,
                        "render": function ( data, type, full, meta ) {
                            let href = '/companies/' + full.id;
                            return '<a href="#" style="" data-href="' + href + '" class="remove-item" >Delete</a>';
                        }
                    }
                ]
            });
        });

    </script>
@stop